Run migrations: take 1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,6 +45,25 @@ commands:
               --stack-name udapeople-frontend-<< parameters.workflow-id >>
             aws cloudformation delete-stack \
              --stack-name udapeople-backend-<< parameters.workflow-id >>
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      workflow-id:
+        type: string
+        default: "{CIRCLE_WORKFLOW_ID:0:7}"
+    steps:
+      - run:
+          name: Revert migrations
+          when: on_fail
+          command: |
+            SUCCESS = $(curl https://kvdb.io/MN5GdbcgXgoRVQJ1wMYokF/migration_<< parameters.workflow-id >>)
+            if [[ $SUCCESS -eq 1 ]] 
+            then
+               cd ~/project/backend
+               npm install
+               npm run migrations:revert
+               exit 1
+            fi
 jobs:
   build-frontend:
     executor: node
@@ -212,21 +231,37 @@ jobs:
             ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
       - destroy-environment:
           workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
-  # run-migrations:
-  #   executor: node
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Run migrations
-  #         command: |
-  #           # Your code here
-  #           exit 1
-  #     - run:
-  #         name: Send migration results to memstash
-  #         command: |
-  #           # Your code here
-  #           exit 1
-  #     # Here's where you will add some code to rollback on failure
+  run-migrations:
+    executor: node
+    working_directory: ~/project
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations:create > migrations_dump.txt
+      - save_cache:
+          paths:
+            - backend/node_modules
+          key: backend-build
+      - run:
+          name: Send migration results to kvdb
+          command: |
+            cat ~/project/backend/migrations_dump.txt
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt; then
+                curl https://kvdb.io/MN5GdbcgXgoRVQJ1wMYokF/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
+                exit 0
+            else
+                curl https://kvdb.io/MN5GdbcgXgoRVQJ1wMYokF/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                exit 1
+            fi
+      - revert-migrations:
+          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # Here's where you will add some code to rollback on failure
 
   # deploy-frontend:
   #   docker:
@@ -285,7 +320,10 @@ workflows:
       # - scan-frontend:
       #     requires:
       #       - build-frontend
-      - deploy-infrastructure
-      - configure-infrastructure:
-          requires:
-            - deploy-infrastructure
+      # - deploy-infrastructure
+      # - configure-infrastructure:
+      #     requires:
+      #       - deploy-infrastructure
+      - run-migrations
+        # requires:
+        #   - configure-infrastructure
